env:
  es2017: true
  browser: true
  commonjs: true

extends: ['htmlacademy/es6', 'plugin:react/recommended']

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 9
  sourceType: module

plugins: ['react']

settings:
  react:
    version: '18'
